from tkinter import *
from tkinter import messagebox
from PIL import Image, ImageTk
root=Tk()
root.geometry("650x400")
root.title("Denomination Countion")
root.configure(bg="Light Blue")
upload = Image.open("app_img.jpg")
upload = upload.resize((300, 300))
image = ImageTk.PhotoImage(upload)
label = Label(root, image=image, bg='light blue')
label.place(x=180, y=20)
label1 = Label(
root,text="Hey User! Welcome to Denomination Counter Application.",bg='light blue')
label1.place(relx=0.5 , y=340)
def topwin():
    top = Toplevel()
    top.title("Denominations Calculator")
    top.configure(bg='light grey')
    top.geometry("600x350+50+50")
    label = Label(top, text="Enter total amount", bg='light grey')
    entry = Entry(top)
    lbl = Label(
        top,
        text="Here are number of notes for each denomination",bg='light grey')
    l1 = Label(top, text="2000", bg='light grey')
    l2 = Label(top, text="500", bg='light grey')
    l3 = Label(top, text="100", bg='light grey')
    t1 = Entry(top)
    t2 = Entry(top)
    t3 = Entry(top)
    label.place(x=230, y=50)
    entry.place(x=200, y=80)
    btn1=Button(top, text='Calculate',bg='brown', fg='white')
    btn1.place(x=240, y=120)
    lbl.place(x=140, y=170)
    l1.place(x=180, y=200)
    l2.place(x=180, y=230)
    l3.place(x=180, y=260)
    t1.place(x=270, y=200)
    t2.place(x=270, y=230)
    t3.place(x=270, y=260)
    messagebox.showerror("Error", "Please enter a valid number.")
    top.mainloop()
def message():
    MsgBox = messagebox.showinfo("Alert", "Do you want to calculate the denomination count?")
    if MsgBox == 'ok':topwin()
btn=Button(text="Lets Get Started" , command=message)
btn.pack()
root.mainloop()